# Generated by Django 5.2.17 on 2026-09-20 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'درباره من', 'verbose_name_plural': 'درباره من'},
        ),
        migrations.AlterModelOptions(
            name='fieldofactivity',
            options={'verbose_name': 'حوزه فعالیت', 'verbose_name_plural': 'حوزه\u200cهای فعالیت'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='usercustom',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل\u200cهای کاربران'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'سابقه کاری', 'verbose_name_plural': 'سوابق کاری'},
        ),
        migrations.AlterModelOptions(
            name='worktechuse',
            options={'verbose_name': 'فناوری استفاده\u200cشده', 'verbose_name_plural': 'فناوری\u200cهای استفاده\u200cشده'},
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='fieldofactivity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام حوزه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک نسخه نمایشی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='field_of_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.fieldofactivity', verbose_name='حوزه فعالیت'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک گیت\u200cهاب'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used',
            field=models.CharField(max_length=200, verbose_name='فناوری\u200cهای استفاده\u200cشده'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام مهارت'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(verbose_name='درصد تسلط'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='معرفی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(max_length=20, verbose_name='عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=100, verbose_name='سمت شغلی'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='worktechuse',
            name='technology',
            field=models.CharField(max_length=50, verbose_name='فناوری'),
        ),
        migrations.AlterField(
            model_name='worktechuse',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.workexperience', verbose_name='سابقه کاری'),
        ),
    ]
