# Generated by Django 5.2.17 on 2026-09-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_aboutme_options_alter_fieldofactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'تجربه کاری', 'verbose_name_plural': 'تجربه\u200cهای کاری'},
        ),
        migrations.AlterField(
            model_name='worktechuse',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.workexperience', verbose_name='تجربه کاری'),
        ),
    ]
