# Generated by Django 5.2.17 on 2026-09-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/projects/', verbose_name='تصویر پروژه'),
        ),
    ]
