# Generated by Django 5.2.17 on 2026-09-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_project_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='project',
            name='project_picture',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='تصویر پروژه'),
        ),
    ]
