# Generated by Django 5.2.17 on 2026-09-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_project_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام گواهینامه')),
                ('issuer', models.CharField(max_length=100, verbose_name='صادرکننده')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ دریافت')),
                ('certificate_link', models.URLField(blank=True, null=True, verbose_name='لینک گواهینامه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usercustom', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گواهینامه',
                'verbose_name_plural': 'گواهینامه‌ها',
            },
        ),
    ]
