# Generated by Django 5.2.17 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان مطلب')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نشانی مطلب')),
                ('excerpt', models.TextField(max_length=300, verbose_name='خلاصه مطلب')),
                ('content', models.TextField(verbose_name='متن مطلب')),
                ('category', models.CharField(max_length=80, verbose_name='دسته‌بندی')),
                ('published_at', models.DateTimeField(verbose_name='تاریخ انتشار')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
            ],
            options={
                'verbose_name': 'مطلب وبلاگ',
                'verbose_name_plural': 'مطالب وبلاگ',
                'ordering': ('-published_at',),
            },
        ),
    ]
